FROM python:3.9.10-alpine3.15

RUN apk add gcc musl-dev python3-dev libffi-dev openssl-dev linux-headers make g++
RUN apk add py3-grpcio>1.29.1 py3-protobuf
RUN apk upgrade
RUN apk add rust cargo
RUN pip3 install --upgrade pip
RUN pip3 install jwcrypto 
RUN pip3 install dazl

WORKDIR /data

ENTRYPOINT python3 auth-service.py

